services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: rent-read-app:v1.0
    container_name: rent-read-app
    ports:
      - "8081:8081"
    environment:
      SPRING_PROFILES_ACTIVE: local
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/test_db
      SPRING_DATASOURCE_USERNAME: assessment
      SPRING_DATASOURCE_PASSWORD: redrum
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.3.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: test_db
      MYSQL_USER: assessment
      MYSQL_PASSWORD: redrum
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin-ui
    restart: always
    ports:
      - "4040:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data: